// SPDX-License-Identifier: Apache-2.0
// Copyright 2025 containd Authors

package services

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"syscall"
	"time"

	commonlog "github.com/tonylturner/containd/pkg/common/logging"
	"github.com/tonylturner/containd/pkg/cp/config"
	"go.uber.org/zap"
)

// NTPManager renders and optionally supervises NTP client configuration.
// Uses chrony (chronyd) as the NTP implementation. Falls back to openntpd
// if chrony is not available and openntpd is present.
type NTPManager struct {
	BaseDir   string
	Supervise bool
	// NTPDPath is the path to the NTP daemon binary (chronyd or openntpd).
	NTPDPath string
	// NTPDName identifies the active implementation ("chrony" or "openntpd").
	NTPDName string
	OnEvent  func(kind string, attrs map[string]any)

	mu         sync.Mutex
	lastCfg    config.NTPConfig
	lastRender time.Time
	lastError  string
	lastStart  time.Time
	lastStop   time.Time
	lastExit   string
	cmd        *exec.Cmd
	log        *zap.SugaredLogger
}

// RecordSync increments NTP telemetry (successful syncs vs failures).
func (m *NTPManager) RecordSync(success int, failures int) {
	if m == nil || m.OnEvent == nil {
		return
	}
	if success > 0 {
		m.emit("service.ntp.sync", map[string]any{"count": success})
	}
	if failures > 0 {
		m.emit("service.ntp.sync_failed", map[string]any{"error_count": failures})
	}
}

func NewNTPManager(baseDir string) *NTPManager {
	if baseDir == "" {
		baseDir = os.Getenv("CONTAIND_SERVICES_DIR")
	}
	if baseDir == "" {
		baseDir = defaultServicesDir
	}
	supervise := true
	if v := strings.TrimSpace(os.Getenv("CONTAIND_SUPERVISE_NTP")); v != "" && v != "1" && !strings.EqualFold(v, "true") {
		supervise = false
	}

	// Prefer chrony (Wolfi), fall back to openntpd (Debian/other).
	ntpdPath, ntpdName := detectNTPD()

	return &NTPManager{
		BaseDir:   baseDir,
		Supervise: supervise,
		NTPDPath:  ntpdPath,
		NTPDName:  ntpdName,
		log:       newNTPLogger(),
	}
}

// detectNTPD finds the best available NTP daemon. Prefers chrony, falls back to openntpd.
func detectNTPD() (path string, name string) {
	// Check for env override first.
	if p := strings.TrimSpace(os.Getenv("CONTAIND_NTPD_PATH")); p != "" {
		if _, err := os.Stat(p); err == nil {
			base := filepath.Base(p)
			if strings.Contains(base, "chrony") {
				return p, "chrony"
			}
			return p, "openntpd"
		}
	}
	// Legacy env var for backward compatibility.
	if p := strings.TrimSpace(os.Getenv("CONTAIND_OPENNTPD_PATH")); p != "" {
		if _, err := os.Stat(p); err == nil {
			return p, "openntpd"
		}
	}
	// Prefer chrony (available in Wolfi).
	if p, ok := detectBinary([]string{"/usr/sbin/chronyd", "/usr/bin/chronyd"}); ok {
		return p, "chrony"
	}
	// Fall back to openntpd (available in Debian/Alpine).
	if p, ok := detectBinary([]string{"/usr/sbin/openntpd", "/usr/bin/openntpd"}); ok {
		return p, "openntpd"
	}
	return "", ""
}

func newNTPLogger() *zap.SugaredLogger {
	lg, err := commonlog.NewZap("ntp", "ntp", commonlog.Options{
		FilePath: "/data/logs/ntp.log",
		JSON:     true,
		Level:    "info",
	})
	if err != nil {
		return zap.NewNop().Sugar()
	}
	return lg
}

func (m *NTPManager) Apply(ctx context.Context, cfg config.NTPConfig) error {
	_ = ctx
	m.mu.Lock()
	m.lastCfg = cfg
	m.mu.Unlock()

	if err := os.MkdirAll(m.BaseDir, 0o755); err != nil {
		return err
	}
	path := m.configPath()
	if !cfg.Enabled {
		m.stopLocked()
		_ = os.Remove(path)
		// Also clean up the other config file name to avoid stale files.
		if m.NTPDName == "chrony" {
			_ = os.Remove(filepath.Join(m.BaseDir, "openntpd.conf"))
		} else {
			_ = os.Remove(filepath.Join(m.BaseDir, "chrony.conf"))
		}
		m.mu.Lock()
		m.lastRender = time.Now().UTC()
		m.lastError = ""
		m.mu.Unlock()
		return nil
	}

	content := m.renderConfig(cfg)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		m.mu.Lock()
		m.lastError = err.Error()
		m.mu.Unlock()
		return err
	}
	if err := m.validate(ctx, path); err != nil {
		return err
	}
	m.mu.Lock()
	m.lastRender = time.Now().UTC()
	m.lastError = ""
	m.mu.Unlock()
	if m.Supervise {
		m.startOrRestart(ctx, path)
	}
	return nil
}

func (m *NTPManager) configPath() string {
	if m.NTPDName == "chrony" {
		return filepath.Join(m.BaseDir, "chrony.conf")
	}
	return filepath.Join(m.BaseDir, "openntpd.conf")
}

// renderConfig produces the appropriate config file content for the active NTP daemon.
func (m *NTPManager) renderConfig(cfg config.NTPConfig) string {
	if m.NTPDName == "chrony" {
		return m.renderChronyConfig(cfg)
	}
	return m.renderOpenNTPDConfig(cfg)
}

func (m *NTPManager) renderChronyConfig(cfg config.NTPConfig) string {
	var b strings.Builder
	b.WriteString("# Generated by containd — do not edit manually.\n")
	for _, s := range cfg.Servers {
		s = strings.TrimSpace(s)
		if s == "" {
			continue
		}
		b.WriteString("server ")
		b.WriteString(s)
		b.WriteString(" iburst")
		if cfg.IntervalSeconds > 0 {
			// chrony uses log2 poll intervals; approximate from seconds.
			poll := intervalToPoll(cfg.IntervalSeconds)
			fmt.Fprintf(&b, " minpoll %d maxpoll %d", poll, poll)
		}
		b.WriteString("\n")
	}
	// Allow the clock to be stepped on first sync (important in containers).
	b.WriteString("\nmakestep 1 -1\n")
	// Drift file for clock rate tracking.
	b.WriteString("driftfile /data/chrony.drift\n")
	// Client-only mode (no NTP server).
	b.WriteString("port 0\ncmdport 0\n")
	return b.String()
}

func (m *NTPManager) renderOpenNTPDConfig(cfg config.NTPConfig) string {
	var b strings.Builder
	for _, s := range cfg.Servers {
		s = strings.TrimSpace(s)
		if s == "" {
			continue
		}
		b.WriteString("servers ")
		b.WriteString(s)
		b.WriteString("\n")
	}
	if cfg.IntervalSeconds > 0 {
		fmt.Fprintf(&b, "\n# poll-interval-seconds: %d\n", cfg.IntervalSeconds)
	}
	return b.String()
}

// intervalToPoll converts seconds to the nearest log2 poll value for chrony.
// chrony poll values: 4=16s, 6=64s, 8=256s, 10=1024s, 12=4096s.
func intervalToPoll(seconds int) int {
	poll := 4 // minimum: 16 seconds
	for v := 16; v < seconds && poll < 17; v *= 2 {
		poll++
	}
	return poll
}

func (m *NTPManager) Current() config.NTPConfig {
	m.mu.Lock()
	defer m.mu.Unlock()
	return m.lastCfg
}

func (m *NTPManager) Status() map[string]any {
	m.mu.Lock()
	defer m.mu.Unlock()
	running := m.cmd != nil && m.cmd.Process != nil
	pid := 0
	if running {
		pid = m.cmd.Process.Pid
	}
	return map[string]any{
		"enabled":          m.lastCfg.Enabled,
		"servers_count":    len(m.lastCfg.Servers),
		"last_render":      m.lastRender.Format(time.RFC3339Nano),
		"last_error":       m.lastError,
		"interval_seconds": m.lastCfg.IntervalSeconds,
		"supervise":        m.Supervise,
		"ntpd_path":        m.NTPDPath,
		"ntpd_name":        m.NTPDName,
		"running":          running,
		"pid":              pid,
		"last_start":       m.lastStart,
		"last_stop":        m.lastStop,
		"last_exit":        m.lastExit,
		// Backward compatibility: keep openntpd_path for existing UI/API consumers.
		"openntpd_path": m.NTPDPath,
	}
}

func (m *NTPManager) validate(ctx context.Context, configPath string) error {
	if !m.lastCfg.Enabled {
		return nil
	}
	if m.NTPDPath == "" {
		m.mu.Lock()
		m.lastError = "NTP daemon not found (validation skipped)"
		m.mu.Unlock()
		m.emit("service.ntp.validate_skipped", map[string]any{"reason": "ntpd missing"})
		return nil
	}

	testCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()

	var cmd *exec.Cmd
	if m.NTPDName == "chrony" {
		// chronyd -p: parse config and exit.
		// nosemgrep: go.lang.security.audit.dangerous-exec-command.dangerous-exec-command
		cmd = exec.CommandContext(testCtx, m.NTPDPath, "-p", "-f", configPath)
	} else {
		// openntpd -n: check config.
		// nosemgrep: go.lang.security.audit.dangerous-exec-command.dangerous-exec-command
		cmd = exec.CommandContext(testCtx, m.NTPDPath, "-n", "-f", configPath)
	}
	if out, err := cmd.CombinedOutput(); err != nil {
		msg := strings.TrimSpace(string(out))
		if msg != "" {
			err = fmt.Errorf("%w: %s", err, msg)
		}
		m.mu.Lock()
		m.lastError = err.Error()
		m.mu.Unlock()
		m.emit("service.ntp.validate_failed", map[string]any{"error": err.Error(), "error_count": 1})
		return err
	}
	return nil
}

func (m *NTPManager) startOrRestart(ctx context.Context, configPath string) {
	m.mu.Lock()
	defer m.mu.Unlock()
	if !m.lastCfg.Enabled {
		return
	}
	if m.NTPDPath == "" {
		m.lastError = "NTP daemon not found; supervision skipped"
		m.emit("service.ntp.start_skipped", map[string]any{"reason": m.lastError})
		m.log.Warnw("NTP daemon not found; supervision skipped")
		return
	}
	if syscall.Geteuid() != 0 {
		m.lastError = "NTP supervision skipped (requires root)"
		m.emit("service.ntp.start_skipped", map[string]any{"reason": m.lastError})
		m.log.Warnw("NTP supervision skipped; not running as root")
		return
	}
	if !hasSysTimeCap() {
		m.lastError = "NTP supervision skipped: CAP_SYS_TIME not available (add --cap-add SYS_TIME to docker run)"
		m.emit("service.ntp.start_skipped", map[string]any{"reason": m.lastError})
		m.log.Warnw("NTP supervision skipped; CAP_SYS_TIME missing")
		return
	}
	if m.cmd != nil && m.cmd.Process != nil {
		_ = m.cmd.Process.Signal(os.Interrupt)
		time.Sleep(50 * time.Millisecond)
	}

	// Use background context so the daemon outlives the API request that triggered it.
	var cmd *exec.Cmd
	if m.NTPDName == "chrony" {
		// chronyd -d: foreground mode; -f: config file.
		// nosemgrep: go.lang.security.audit.dangerous-exec-command.dangerous-exec-command
		cmd = exec.CommandContext(context.Background(), m.NTPDPath, "-d", "-f", configPath)
	} else {
		// openntpd -d: foreground mode; -f: config file.
		// nosemgrep: go.lang.security.audit.dangerous-exec-command.dangerous-exec-command
		cmd = exec.CommandContext(context.Background(), m.NTPDPath, "-d", "-f", configPath)
	}
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		m.lastError = err.Error()
		m.emit("service.ntp.start_failed", map[string]any{"error": err.Error(), "error_count": 1})
		m.log.Errorw("failed to start NTP daemon", "impl", m.NTPDName, "error", err)
		return
	}
	m.cmd = cmd
	m.lastError = ""
	m.lastStart = time.Now().UTC()
	m.log.Infow("started NTP daemon", "impl", m.NTPDName, "pid", cmd.Process.Pid, "config", configPath)
	m.emit("service.ntp.started", map[string]any{"pid": cmd.Process.Pid, "config": configPath, "impl": m.NTPDName, "count": 1})

	// Channel to detect early exit (e.g., missing CAP_SYS_TIME).
	earlyExit := make(chan string, 1)
	go func() {
		err := cmd.Wait()
		exit := "ok"
		if err != nil {
			exit = err.Error()
		}
		m.mu.Lock()
		m.lastExit = exit
		m.lastStop = time.Now().UTC()
		if exit != "ok" {
			m.lastError = "NTP daemon exited unexpectedly: " + exit + " (check CAP_SYS_TIME capability)"
		}
		m.cmd = nil
		m.mu.Unlock()
		m.log.Infow("NTP daemon exited", "impl", m.NTPDName, "pid", cmd.Process.Pid, "exit", exit)
		m.emit("service.ntp.exited", map[string]any{"pid": cmd.Process.Pid, "exit": exit, "error_count": 1})
		earlyExit <- exit
	}()

	// Brief stability check: if the daemon dies within 1 second, report failure immediately.
	select {
	case exit := <-earlyExit:
		if exit != "ok" {
			m.log.Errorw("NTP daemon failed immediately after start", "impl", m.NTPDName, "exit", exit)
		}
	case <-time.After(1 * time.Second):
		// Daemon survived initial startup — considered stable.
	}
}

func (m *NTPManager) stopLocked() {
	if m.cmd != nil && m.cmd.Process != nil {
		_ = m.cmd.Process.Signal(os.Interrupt)
		m.log.Infow("stopped NTP daemon", "impl", m.NTPDName, "pid", m.cmd.Process.Pid)
		m.emit("service.ntp.stopped", map[string]any{"pid": m.cmd.Process.Pid, "count": 1})
		m.lastStop = time.Now().UTC()
		m.lastExit = "stopped"
	}
	m.cmd = nil
}

func (m *NTPManager) emit(kind string, attrs map[string]any) {
	if m == nil || m.OnEvent == nil {
		return
	}
	m.OnEvent(kind, attrs)
}
